# Generated by Django 4.1.7 on 2023-03-08 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_ended',
            field=models.BooleanField(default=False),
        ),
    ]
